name: Bug Report
description: File a bug report to help us improve the plugin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: jellyfin-version
    attributes:
      label: Jellyfin Version
      description: What version of Jellyfin are you running?
      placeholder: e.g., 10.9.11
    validations:
      required: true
      
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the Audio Tagger plugin are you using?
      placeholder: e.g., 1.0.0.0
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform is Jellyfin running on?
      options:
        - Windows
        - Linux
        - macOS
        - Docker
        - Other
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (enable verbose logging first).
      render: shell
