name: Feature Request
description: Suggest an idea for the Audio Tagger plugin
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why this feature would be useful.
      placeholder: Describe your use case and how this would solve a problem.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered.
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information that might be helpful.
