<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)" />
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(HostingAbstractionsVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Jellyfin.Plugin.AudioTagger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\manifest.json" Link="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
